//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuApplication.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_EmployeePosition
    {
        public int IDEmployee { get; set; }
        public string NameEmployee { get; set; }
        public string SurnameEmployee { get; set; }
        public string PatronymicEmloyee { get; set; }
        public string ShortNameEmployee { get; set; }
        public int IDPosition { get; set; }
        public string NamePosition { get; set; }
    }
}
