//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuApplication.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_OrganizationSubdivision
    {
        public int IDOrganization { get; set; }
        public string NameOrganization { get; set; }
        public int IDSubdivision { get; set; }
        public string NameSubdivision { get; set; }
    }
}
