//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuApplication.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MenuSubdivision
    {
        public Nullable<int> IDCalculator { get; set; }
        public int IDChiefCooker { get; set; }
        public int IDMenu { get; set; }
        public int IDTypeMenu { get; set; }
        public System.DateTime UseDate { get; set; }
        public int IDSubdivision { get; set; }
        public string NameSubdivision { get; set; }
    }
}
