//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuApplication.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MenuEmployeePosition
    {
        public int IDMenu { get; set; }
        public int IDSubdivision { get; set; }
        public int IDTypeMenu { get; set; }
        public System.DateTime UseDate { get; set; }
        public int IDChiefCooker { get; set; }
        public string NameChiefCooker { get; set; }
        public string SurnameChiefCooker { get; set; }
        public string PatronymicChiefCooker { get; set; }
        public string ShortNameChiefCooker { get; set; }
        public int IDPositionChiefCooker { get; set; }
        public string NamePositionChiefCooker { get; set; }
        public Nullable<int> IDCalculator { get; set; }
        public string NameCalculator { get; set; }
        public string SurnameCalculator { get; set; }
        public string PatronymicCalculator { get; set; }
        public string ShortNameCalculator { get; set; }
        public int IDPositionCalculator { get; set; }
        public string NamePositionCalculator { get; set; }
    }
}
