//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuApplication.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ListDishes
    {
        public string NameDish { get; set; }
        public string ExpandedNameDish { get; set; }
        public string WeightDish { get; set; }
        public string NumberInCollectionOfRecipes { get; set; }
        public int IDTypeDish { get; set; }
        public string NameIngredient { get; set; }
    }
}
